--------------------------------------------------------
-- Archivo creado  - sábado-mayo-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BIBLIOTECARIO
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."BIBLIOTECARIO" 
   (	"ID_BIBLIOTECARIO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CONTRATO" NUMBER(*,0), 
	"IDUSUARIO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARRERAS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CARRERAS" 
   (	"ID_CARRERA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."CATEGORIA" 
   (	"IDCATEGORIA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRECATEGORIA" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTE
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."ESTUDIANTE" 
   (	"ID_ESTUDIANTE" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MATRICULA" VARCHAR2(20 BYTE), 
	"IDCARRERA" NUMBER(*,0), 
	"IDUSUARIO" NUMBER(*,0), 
	"IDFACULTAD" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTAD
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."FACULTAD" 
   (	"ID_FACULTAD" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FINANZAS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."FINANZAS" 
   (	"ID_FINANZA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHAREGISTRO" DATE, 
	"TIPOMOVIMIENTO" VARCHAR2(20 BYTE), 
	"MONTOTOTAL" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IDIOMA
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."IDIOMA" 
   (	"ID_IDIOMA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBREIDIOMA" VARCHAR2(20 BYTE), 
	"CODIGOISO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIAL
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."MATERIAL" 
   (	"ID_MATERIAL" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" VARCHAR2(20 BYTE), 
	"AUTOR" VARCHAR2(20 BYTE), 
	"ANIOPUBLICACION" VARCHAR2(20 BYTE), 
	"TIPOMATERIAL" VARCHAR2(20 BYTE), 
	"STOCKDISPONIBLE" NUMBER(*,0), 
	"IMAGEN_PORTADA" VARCHAR2(60 BYTE), 
	"IDCATEGORIA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIAL_IDIOMA
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."MATERIAL_IDIOMA" 
   (	"ID_IDIOMA" NUMBER(*,0), 
	"ID_MATERIAL" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBRESIA
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."MEMBRESIA" 
   (	"ID_MEMBRESIA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NUMERO_CARNET" VARCHAR2(20 BYTE), 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE, 
	"ESTADO" NUMBER(*,0), 
	"IDUSUARIO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MULTA
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."MULTA" 
   (	"ID_MULTA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MONTO" NUMBER(*,0), 
	"FECHAGENERADA" DATE, 
	"PAGADA" NUMBER(*,0), 
	"IDPRESTAMO" NUMBER(*,0), 
	"IDFINANZA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERMISOS_REGISTRADOS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."PERMISOS_REGISTRADOS" 
   (	"ID_PERMISO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_PERMISO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRESTAMO
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."PRESTAMO" 
   (	"ID_PRESTAMO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHAPRESTAMO" DATE, 
	"FECHADEVOLUCION" DATE, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"IDUSUARIO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRESTAMO_MATERIAL
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."PRESTAMO_MATERIAL" 
   (	"IDPRESTAMOS" NUMBER(*,0), 
	"IDMATERIAL" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFESOR
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."PROFESOR" 
   (	"ID_PROFESOR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DEPARTAMENTO" VARCHAR2(20 BYTE), 
	"IDUSUARIO" NUMBER(*,0), 
	"ID_CONTRATO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES_PERMISOS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."ROLES_PERMISOS" 
   (	"ID_ROL" NUMBER(*,0), 
	"ID_PERMISO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES_REGISTRADOS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."ROLES_REGISTRADOS" 
   (	"ID_ROL" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE_ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."TIPO_CONTRATO" 
   (	"ID_CONTRATO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TIPO" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOKENS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."TOKENS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TOKEN" VARCHAR2(40 BYTE), 
	"TOKENTYPE" VARCHAR2(20 BYTE), 
	"REVOKED" NUMBER(*,0), 
	"EXPIRED" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERTOKEN
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."USERTOKEN" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."USUARIO" 
   (	"IDUSUARIO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CARNET" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO1" VARCHAR2(30 BYTE), 
	"APELLIDO2" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"FECHAREGISTRO" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS_MORA
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."USUARIOS_MORA" 
   (	"ID_USUARIO_MORA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDMULTA" NUMBER(*,0), 
	"ESTADOPENALIZACION" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS_REGISTRADOS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."USUARIOS_REGISTRADOS" 
   (	"ID_REGISTRADO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 79 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBREUSUARIO" VARCHAR2(20 BYTE), 
	"CONTRASENIA" VARCHAR2(20 BYTE), 
	"ISENABLED" NUMBER(*,0), 
	"ACCOUNTNOEXPIRED" NUMBER, 
	"ACCOUNTNOLOCKED" NUMBER, 
	"CREDENTIALNOEXPIRED" NUMBER, 
	"USUARIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS_ROLES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."USUARIOS_ROLES" 
   (	"ID_REGISTRADO" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ADMIN.BIBLIOTECARIO
SET DEFINE OFF;
REM INSERTING into C##ADMIN.CARRERAS
SET DEFINE OFF;
Insert into C##ADMIN.CARRERAS (ID_CARRERA,NOMBRE,DESCRIPCION) values (1,'INGENIERIA DE SISTEMAS',null);
Insert into C##ADMIN.CARRERAS (ID_CARRERA,NOMBRE,DESCRIPCION) values (2,'INGENIERIA INDUSTRIAL',null);
REM INSERTING into C##ADMIN.CATEGORIA
SET DEFINE OFF;
REM INSERTING into C##ADMIN.ESTUDIANTE
SET DEFINE OFF;
REM INSERTING into C##ADMIN.FACULTAD
SET DEFINE OFF;
REM INSERTING into C##ADMIN.FINANZAS
SET DEFINE OFF;
REM INSERTING into C##ADMIN.IDIOMA
SET DEFINE OFF;
REM INSERTING into C##ADMIN.MATERIAL
SET DEFINE OFF;
REM INSERTING into C##ADMIN.MATERIAL_IDIOMA
SET DEFINE OFF;
REM INSERTING into C##ADMIN.MEMBRESIA
SET DEFINE OFF;
REM INSERTING into C##ADMIN.MULTA
SET DEFINE OFF;
REM INSERTING into C##ADMIN.PERMISOS_REGISTRADOS
SET DEFINE OFF;
Insert into C##ADMIN.PERMISOS_REGISTRADOS (ID_PERMISO,NOMBRE_PERMISO) values (4,'CREATE');
Insert into C##ADMIN.PERMISOS_REGISTRADOS (ID_PERMISO,NOMBRE_PERMISO) values (5,'READ');
Insert into C##ADMIN.PERMISOS_REGISTRADOS (ID_PERMISO,NOMBRE_PERMISO) values (6,'UPDATE');
Insert into C##ADMIN.PERMISOS_REGISTRADOS (ID_PERMISO,NOMBRE_PERMISO) values (7,'DELETE');
Insert into C##ADMIN.PERMISOS_REGISTRADOS (ID_PERMISO,NOMBRE_PERMISO) values (8,'REFACTOR');
REM INSERTING into C##ADMIN.PRESTAMO
SET DEFINE OFF;
REM INSERTING into C##ADMIN.PRESTAMO_MATERIAL
SET DEFINE OFF;
REM INSERTING into C##ADMIN.PROFESOR
SET DEFINE OFF;
REM INSERTING into C##ADMIN.ROLES_PERMISOS
SET DEFINE OFF;
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (4,4);
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (4,5);
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (4,6);
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (4,7);
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (41,4);
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (41,5);
Insert into C##ADMIN.ROLES_PERMISOS (ID_ROL,ID_PERMISO) values (41,6);
REM INSERTING into C##ADMIN.ROLES_REGISTRADOS
SET DEFINE OFF;
Insert into C##ADMIN.ROLES_REGISTRADOS (ID_ROL,NOMBRE_ROL) values (2,'ESTUDIANTE');
Insert into C##ADMIN.ROLES_REGISTRADOS (ID_ROL,NOMBRE_ROL) values (3,'BIBLIOTECARIO');
Insert into C##ADMIN.ROLES_REGISTRADOS (ID_ROL,NOMBRE_ROL) values (4,'ADMIN');
Insert into C##ADMIN.ROLES_REGISTRADOS (ID_ROL,NOMBRE_ROL) values (41,'PROFESOR');
REM INSERTING into C##ADMIN.TIPO_CONTRATO
SET DEFINE OFF;
REM INSERTING into C##ADMIN.TOKENS
SET DEFINE OFF;
REM INSERTING into C##ADMIN.USERTOKEN
SET DEFINE OFF;
REM INSERTING into C##ADMIN.USUARIO
SET DEFINE OFF;
REM INSERTING into C##ADMIN.USUARIOS_MORA
SET DEFINE OFF;
REM INSERTING into C##ADMIN.USUARIOS_REGISTRADOS
SET DEFINE OFF;
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (159,'carlos','123456',1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (22,'administrador','123456',1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (43,'gabrielactualizado12','gabriel',1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (41,'carlos','carlos503',1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (42,'miguel',null,1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (119,'reyactualizadorol','123456',1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (121,'maso','123456',1,1,1,1,null);
Insert into C##ADMIN.USUARIOS_REGISTRADOS (ID_REGISTRADO,NOMBREUSUARIO,CONTRASENIA,ISENABLED,ACCOUNTNOEXPIRED,ACCOUNTNOLOCKED,CREDENTIALNOEXPIRED,USUARIO_ID) values (122,'gabrielin','123456',1,1,1,1,null);
REM INSERTING into C##ADMIN.USUARIOS_ROLES
SET DEFINE OFF;
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (22,4);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (41,3);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (42,2);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (43,3);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (119,3);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (121,2);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (122,3);
Insert into C##ADMIN.USUARIOS_ROLES (ID_REGISTRADO,ID_ROL) values (159,41);
--------------------------------------------------------
--  DDL for Index BIBLIOTECARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."BIBLIOTECARIO_PK" ON "C##ADMIN"."BIBLIOTECARIO" ("ID_BIBLIOTECARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARRERAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CARRERAS_PK" ON "C##ADMIN"."CARRERAS" ("ID_CARRERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."CATEGORIA_PK" ON "C##ADMIN"."CATEGORIA" ("IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."ESTUDIANTE_PK" ON "C##ADMIN"."ESTUDIANTE" ("ID_ESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."FACULTAD_PK" ON "C##ADMIN"."FACULTAD" ("ID_FACULTAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FINANZAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."FINANZAS_PK" ON "C##ADMIN"."FINANZAS" ("ID_FINANZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDIOMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."IDIOMA_PK" ON "C##ADMIN"."IDIOMA" ("ID_IDIOMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MATERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."MATERIAL_PK" ON "C##ADMIN"."MATERIAL" ("ID_MATERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBRESIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."MEMBRESIA_PK" ON "C##ADMIN"."MEMBRESIA" ("ID_MEMBRESIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MULTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."MULTA_PK" ON "C##ADMIN"."MULTA" ("ID_MULTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERMISOS_REGISTRADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."PERMISOS_REGISTRADOS_PK" ON "C##ADMIN"."PERMISOS_REGISTRADOS" ("ID_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRESTAMO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."PRESTAMO_PK" ON "C##ADMIN"."PRESTAMO" ("ID_PRESTAMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRESTAMO_MATERIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."PRESTAMO_MATERIAL_PK" ON "C##ADMIN"."PRESTAMO_MATERIAL" ("IDPRESTAMOS", "IDMATERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."PROFESOR_PK" ON "C##ADMIN"."PROFESOR" ("ID_PROFESOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PERMISOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."ROLES_PERMISOS_PK" ON "C##ADMIN"."ROLES_PERMISOS" ("ID_ROL", "ID_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_REGISTRADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."ROLES_REGISTRADOS_PK" ON "C##ADMIN"."ROLES_REGISTRADOS" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPO_CONTRATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."TIPO_CONTRATO_PK" ON "C##ADMIN"."TIPO_CONTRATO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOKENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."TOKENS_PK" ON "C##ADMIN"."TOKENS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERTOKEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USERTOKEN_PK" ON "C##ADMIN"."USERTOKEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USUARIO_PK" ON "C##ADMIN"."USUARIO" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_MORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USUARIOS_MORA_PK" ON "C##ADMIN"."USUARIOS_MORA" ("ID_USUARIO_MORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_REGISTRADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USUARIOS_REGISTRADOS_PK" ON "C##ADMIN"."USUARIOS_REGISTRADOS" ("ID_REGISTRADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."USUARIOS_ROLES_PK" ON "C##ADMIN"."USUARIOS_ROLES" ("ID_REGISTRADO", "ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BIBLIOTECARIO
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."BIBLIOTECARIO" MODIFY ("ID_BIBLIOTECARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BIBLIOTECARIO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BIBLIOTECARIO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."BIBLIOTECARIO" ADD CONSTRAINT "BIBLIOTECARIO_PK" PRIMARY KEY ("ID_BIBLIOTECARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARRERAS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CARRERAS" MODIFY ("ID_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CARRERAS" ADD CONSTRAINT "CARRERAS_PK" PRIMARY KEY ("ID_CARRERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."CATEGORIA" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."ESTUDIANTE" MODIFY ("ID_ESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ESTUDIANTE" MODIFY ("IDCARRERA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ESTUDIANTE" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ESTUDIANTE" MODIFY ("IDFACULTAD" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_PK" PRIMARY KEY ("ID_ESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTAD
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."FACULTAD" MODIFY ("ID_FACULTAD" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."FACULTAD" ADD CONSTRAINT "FACULTAD_PK" PRIMARY KEY ("ID_FACULTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINANZAS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."FINANZAS" MODIFY ("ID_FINANZA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."FINANZAS" ADD CONSTRAINT "FINANZAS_PK" PRIMARY KEY ("ID_FINANZA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IDIOMA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."IDIOMA" MODIFY ("ID_IDIOMA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."IDIOMA" ADD CONSTRAINT "IDIOMA_PK" PRIMARY KEY ("ID_IDIOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIAL
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MATERIAL" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MATERIAL" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MATERIAL" ADD CONSTRAINT "MATERIAL_PK" PRIMARY KEY ("ID_MATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIAL_IDIOMA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MATERIAL_IDIOMA" MODIFY ("ID_IDIOMA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MATERIAL_IDIOMA" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBRESIA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MEMBRESIA" MODIFY ("ID_MEMBRESIA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MEMBRESIA" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MEMBRESIA" ADD CONSTRAINT "MEMBRESIA_PK" PRIMARY KEY ("ID_MEMBRESIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MULTA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MULTA" MODIFY ("ID_MULTA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MULTA" MODIFY ("IDPRESTAMO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MULTA" MODIFY ("IDFINANZA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."MULTA" ADD CONSTRAINT "MULTA_PK" PRIMARY KEY ("ID_MULTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERMISOS_REGISTRADOS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PERMISOS_REGISTRADOS" MODIFY ("ID_PERMISO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PERMISOS_REGISTRADOS" ADD CONSTRAINT "PERMISOS_REGISTRADOS_PK" PRIMARY KEY ("ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESTAMO
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PRESTAMO" MODIFY ("ID_PRESTAMO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PRESTAMO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PRESTAMO" ADD CONSTRAINT "PRESTAMO_PK" PRIMARY KEY ("ID_PRESTAMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESTAMO_MATERIAL
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PRESTAMO_MATERIAL" MODIFY ("IDPRESTAMOS" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PRESTAMO_MATERIAL" MODIFY ("IDMATERIAL" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PRESTAMO_MATERIAL" ADD CONSTRAINT "PRESTAMO_MATERIAL_PK" PRIMARY KEY ("IDPRESTAMOS", "IDMATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PROFESOR" MODIFY ("ID_PROFESOR" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PROFESOR" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PROFESOR" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."PROFESOR" ADD CONSTRAINT "PROFESOR_PK" PRIMARY KEY ("ID_PROFESOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES_PERMISOS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."ROLES_PERMISOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ROLES_PERMISOS" MODIFY ("ID_PERMISO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ROLES_PERMISOS" ADD CONSTRAINT "ROLES_PERMISOS_PK" PRIMARY KEY ("ID_ROL", "ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES_REGISTRADOS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."ROLES_REGISTRADOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."ROLES_REGISTRADOS" ADD CONSTRAINT "ROLES_REGISTRADOS_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_CONTRATO
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."TIPO_CONTRATO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."TIPO_CONTRATO" ADD CONSTRAINT "TIPO_CONTRATO_PK" PRIMARY KEY ("ID_CONTRATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TOKENS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."TOKENS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."TOKENS" ADD CONSTRAINT "TOKENS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADMIN"."TOKENS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERTOKEN
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USERTOKEN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USERTOKEN" ADD CONSTRAINT "USERTOKEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ADMIN"."USUARIO" MODIFY ("APELLIDO1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS_MORA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIOS_MORA" MODIFY ("ID_USUARIO_MORA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIOS_MORA" MODIFY ("IDMULTA" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIOS_MORA" MODIFY ("ESTADOPENALIZACION" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIOS_MORA" ADD CONSTRAINT "USUARIOS_MORA_PK" PRIMARY KEY ("ID_USUARIO_MORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS_REGISTRADOS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIOS_REGISTRADOS" MODIFY ("ID_REGISTRADO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIOS_REGISTRADOS" ADD CONSTRAINT "USUARIOS_REGISTRADOS_PK" PRIMARY KEY ("ID_REGISTRADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS_ROLES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIOS_ROLES" MODIFY ("ID_REGISTRADO" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIOS_ROLES" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."USUARIOS_ROLES" ADD CONSTRAINT "USUARIOS_ROLES_PK" PRIMARY KEY ("ID_REGISTRADO", "ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BIBLIOTECARIO
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."BIBLIOTECARIO" ADD CONSTRAINT "BIBLIOTECARIO_FK1" FOREIGN KEY ("ID_CONTRATO")
	  REFERENCES "C##ADMIN"."TIPO_CONTRATO" ("ID_CONTRATO") ENABLE;
  ALTER TABLE "C##ADMIN"."BIBLIOTECARIO" ADD CONSTRAINT "BIBLIOTECARIO_FK2" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "C##ADMIN"."USUARIO" ("IDUSUARIO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTE
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_FK1" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "C##ADMIN"."USUARIO" ("IDUSUARIO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ADMIN"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_FK2" FOREIGN KEY ("IDCARRERA")
	  REFERENCES "C##ADMIN"."CARRERAS" ("ID_CARRERA") ENABLE;
  ALTER TABLE "C##ADMIN"."ESTUDIANTE" ADD CONSTRAINT "ESTUDIANTE_FK3" FOREIGN KEY ("IDFACULTAD")
	  REFERENCES "C##ADMIN"."FACULTAD" ("ID_FACULTAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIAL
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MATERIAL" ADD CONSTRAINT "MATERIAL_FK1" FOREIGN KEY ("IDCATEGORIA")
	  REFERENCES "C##ADMIN"."CATEGORIA" ("IDCATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIAL_IDIOMA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MATERIAL_IDIOMA" ADD CONSTRAINT "MATERIAL_IDIOMA_FK1" FOREIGN KEY ("ID_IDIOMA")
	  REFERENCES "C##ADMIN"."IDIOMA" ("ID_IDIOMA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ADMIN"."MATERIAL_IDIOMA" ADD CONSTRAINT "MATERIAL_IDIOMA_FK2" FOREIGN KEY ("ID_MATERIAL")
	  REFERENCES "C##ADMIN"."MATERIAL" ("ID_MATERIAL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBRESIA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MEMBRESIA" ADD CONSTRAINT "MEMBRESIA_FK1" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "C##ADMIN"."USUARIO" ("IDUSUARIO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MULTA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."MULTA" ADD CONSTRAINT "MULTA_FK1" FOREIGN KEY ("IDPRESTAMO")
	  REFERENCES "C##ADMIN"."PRESTAMO" ("ID_PRESTAMO") ENABLE;
  ALTER TABLE "C##ADMIN"."MULTA" ADD CONSTRAINT "MULTA_FK2" FOREIGN KEY ("IDFINANZA")
	  REFERENCES "C##ADMIN"."FINANZAS" ("ID_FINANZA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESTAMO
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PRESTAMO" ADD CONSTRAINT "PRESTAMO_FK1" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "C##ADMIN"."USUARIO" ("IDUSUARIO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESTAMO_MATERIAL
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PRESTAMO_MATERIAL" ADD CONSTRAINT "PRESTAMO_MATERIAL_FK1" FOREIGN KEY ("IDPRESTAMOS")
	  REFERENCES "C##ADMIN"."PRESTAMO" ("ID_PRESTAMO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ADMIN"."PRESTAMO_MATERIAL" ADD CONSTRAINT "PRESTAMO_MATERIAL_FK2" FOREIGN KEY ("IDMATERIAL")
	  REFERENCES "C##ADMIN"."MATERIAL" ("ID_MATERIAL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."PROFESOR" ADD CONSTRAINT "PROFESOR_FK1" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "C##ADMIN"."USUARIO" ("IDUSUARIO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ADMIN"."PROFESOR" ADD CONSTRAINT "PROFESOR_FK2" FOREIGN KEY ("ID_CONTRATO")
	  REFERENCES "C##ADMIN"."TIPO_CONTRATO" ("ID_CONTRATO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLES_PERMISOS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."ROLES_PERMISOS" ADD CONSTRAINT "ROLES_PERMISOS_FK1" FOREIGN KEY ("ID_ROL")
	  REFERENCES "C##ADMIN"."ROLES_REGISTRADOS" ("ID_ROL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ADMIN"."ROLES_PERMISOS" ADD CONSTRAINT "ROLES_PERMISOS_FK2" FOREIGN KEY ("ID_PERMISO")
	  REFERENCES "C##ADMIN"."PERMISOS_REGISTRADOS" ("ID_PERMISO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOKENS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."TOKENS" ADD CONSTRAINT "TOKENS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##ADMIN"."USERTOKEN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS_MORA
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIOS_MORA" ADD CONSTRAINT "USUARIOS_MORA_FK1" FOREIGN KEY ("IDMULTA")
	  REFERENCES "C##ADMIN"."MULTA" ("ID_MULTA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS_REGISTRADOS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIOS_REGISTRADOS" ADD CONSTRAINT "USUARIOS_REGISTRADOS_FK1" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "C##ADMIN"."USUARIO" ("IDUSUARIO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS_ROLES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."USUARIOS_ROLES" ADD CONSTRAINT "USUARIOS_ROLES_FK1" FOREIGN KEY ("ID_REGISTRADO")
	  REFERENCES "C##ADMIN"."USUARIOS_REGISTRADOS" ("ID_REGISTRADO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ADMIN"."USUARIOS_ROLES" ADD CONSTRAINT "USUARIOS_ROLES_FK2" FOREIGN KEY ("ID_ROL")
	  REFERENCES "C##ADMIN"."ROLES_REGISTRADOS" ("ID_ROL") ON DELETE CASCADE ENABLE;
